print ("Nume: Ciomschi")
print ("Prenume: Giuliano")
print ("Vârsta: 15 ani")
print ("Adresa: str. Sadovaia 42/a, mun. Bălți")
print ("Telefon: 079971786")
print ("E-mail: giuliano.ciomschi1@gmail.com")
print ("Naționalitate: Republica Moldova")

print ("Competențe de comunicare:")
print ("Competențe de comunicare dobândite prin experiența proprie, comunicare cu persoane ce dețin un nivel înalt de cunoaștere a limbilor străine;")
print ("Capacitatea de a folosi un vocabular vast;")
print ("Capacitatea de a asculta atent și de a asimila multa informație.")

print ("Competențe organizaționale:")
print ("Capacitate de multitasking;")
print ("Teamwork;")
print ("Leadership;")
print ("Social entrepreneurship;")
print ("Critical thinking;")
print ("Responsability;")
print ("Innovation.")
